### ISSUE TITLE
Add a changelog so consumers of this module know what changes actually affect them rather than having them go through your commit history

### ISSUE THREAD

**Issue by balupton** [kemitchell/spdx.js#17]
Would be nice, as right now with the spdx 0.5 release (we currently use 0.4) I had to go to your repo, to find no changelog that tells me what to expect, so instead I have to go through the commit history, as they seem mostly internal changes and I can't be bothered going through each individual commit's changes, I just have to install it and wing it without knowing if anything actually affects me.

To help out, the changelog format that we use:

https://github.com/bevry/projectz/blob/master/HISTORY.md

We also use https://github.com/bevry/projectz to auto-generate and keep up to date a lot of our README files too, such as including the link to the changeling file in our README

All our projects also make use of this file https://github.com/bevry/base/blob/master/CONTRIBUTING.md that explains our changelog format.

**Comment by kemitchell** [comment]
Benjamin, thank you for your message! I'm glad to hear you're getting some use out of the package, and sorry to hear you had to read my lousy commit messages.

The latest 0.5 release was something of a penance, after a bungled release on the 0.4.x line that inadvertently nuked some functionality in a semver-major way. The larger overall picture is that if you have control of your deps, you should look to the smaller packages into which spdx itself has been split:
1. https://www.npmjs.com/package/spdx-expression-parse
2. https://www.npmjs.com/package/spdx-satisfies
3. https://www.npmjs.com/package/spdx-to-html
4. https://www.npmjs.com/package/spdx-expression-validate
5. https://www.npmjs.com/package/spdx-compare

You may have already noticed these, as substitutes for 0.5.

spdx itself is more or less deprecated, but since it's still built into a fair number of old npm releases, I'm loathe to mark it in the public registry. In the meantime, a number of improvements have landed in the new, smaller packages, including from other folks who are now contributors on the repos.

My hope is that those smaller packages will lighten up `npm install`, browser bundles, and npm itself with less unused cruft, as well as reduce the surface area for API changes.

**Comment by balupton** [comment]
Would you be able to send a PR for https://github.com/bevry/projectz to update the relevant packages. I'm not really sure what needs to change, and too busy to implement the update.
