### ISSUE TITLE
What kind of logical operation is `satisfies`?

### ISSUE THREAD

**Issue by phadej** [kemitchell/spdx.js#8]
`semver.satisfies` is of type `(ver : Version, range : VersionRange) -> bool`. Informally _is `ver` in `range`_.

if `spdx.satisfies` would be `(lic : License, expr : LicenseExpression) -> bool`, it could also be informally `lic` is in `expr`.

``` js
spdx.satisfies('MIT', 'MIT'); // => true
spdx.satisfies('MIT', '(ISC OR MIT)'); // => true
spdx.satisfies('Zlib', '(ISC OR (MIT OR Zlib))'); // => true
spdx.satisfies('GPL-3.0', '(ISC OR MIT)'); // => false
spdx.satisfies('GPL-2.0', 'GPL-2.0+'); // => true
spdx.satisfies('GPL-3.0', 'GPL-2.0+'); // => true
spdx.satisfies('GPL-1.0', 'GPL-2.0+'); // => false
```

examples give that intuition. `GPL-3.0` is in `GPL-2.0+`, which is `GPL-2.0` or `GPL-3.0` or newer.

Yet later examples include `(expr1: LicenseExpression, expr2: LicenseExpression) -> bool` versions:

``` js
spdx.satisfies('(MIT OR GPL-2.0)', '(ISC OR MIT)'); // => true
spdx.satisfies('(MIT AND GPL-2.0)', '(MIT OR GPL-2.0)'); // => true
spdx.satisfies('(MIT AND GPL-2.0)', '(ISC OR GPL-2.0)'); // => false
```

And I don't understand what function this is.
It's not `expr1 ≤ expr2` in [lattice-order](http://en.wikipedia.org/wiki/Lattice_%28order%29). The first example fails: `MIT OR GPL-2.0 ≰ ISC OR MIT`

The partial-ordering would be easy to explain, and there is reasonable usecase. If `expr2` is a packages's license (e.g. `GPL-2.0+`, and `expr1` (e.g. `MIT AND BSD-3-Clause AND GPL-3.0+` specifies which licenses we could use, than
if `expr1 ≤ expr2` holds (which it does), we can use the package.

The implication `tautology (expr1 → expr2)` is the same function. "If we have `expr1` we always satisfy `expr2`".

**Comment by kemitchell** [comment]
Thanks for your comment! While I'm not familiar with some of the terminology you use, especially in your final paragraphs, I think I may be able to shed some light.

First and foremost, I should point out that `satisfies` is highly experimental. The SPDX License Expression spec gives some concrete examples of `AND` and `OR` combinations, but isn't as rigorous as I might like. I plan to send feedback when I've time to write it up succinctly. In the meantime, the notion of using license expressions both as statements of license terms and also as criteria for acceptable licensing is my own. `satisfies` is an extension by analogy to node-semver, and not part of the SPDX spec.

I think the notion of one syntax for two purposes---describing license terms offered by a licensor versus describing which licenses are acceptable to a licensee---might be at the heart of your question about `satisfies(expression, expression)`. The first argument to `satisfies` always describes the licensing terms of a specific package, while the other is a statement of policy about acceptable licenses. (This is node-semver's argument order, as well.) Thus the arguments' syntax is the same, but their semantics are subtly different. The presumption with respect to a license policy is that only expressly permitted licenses are allowed. Thus `satisfies('(MIT OR GPL-2.0)', '(ISC OR MIT)')` because `MIT` is one several options from which a licensee can choose for a package, and policy includes `MIT` among acceptable licenses.

Please let me know if I've missed the mark, or how I could make my point better in your terms. I'm very grateful for feedback on this feature in particular!

**Comment by phadej** [comment]
Ok so idea is so the first expression is packages' license, and second is a license policy, than the example where packages's license is `MIT OR GPL-2.0` and we accept packages with `ISC` or `MIT` licenses so the it's feels natural to write `ISC OR MIT`.

Yet if we write `ISC AND MIT` the expression `ISC AND MIT ≤ ISC OR MIT` is true.

That could be expressed as

``` js
satisfies(expr1, expr2) = dual(expr2) ≤ expr1
```

where `dual` swaps `AND`s and `OR`s.

## Complicated policy:

The complicated license policy could be:

```
GPL-3.0+ OR MIT OR (Apache-2.0 AND (MPL-1.0 OR MPL-2.0))
```

i.e. we accept GPL-3.0+, MIT, or packages licenses under both Apache-2.0 and (MPL-1.0 OR MPL-2.0). Than:

``` js
satisfies("Zlib OR MIT", "GPL-3.0 OR MIT OR (Apache-2.0 AND (MPL-1.0 OR MPL-2.0))"); // true

satisfies("MPL-1.0",  "GPL-3.0 OR MIT OR (Apache-2.0 AND (MPL-1.0 OR MPL-2.0))"); // false
// because we need both Apache-2.0 and MPL-1.0!

satisfies("MPL-1.0 OR Apache-2.0", "GPL-3.0 OR MIT OR (Apache-2.0 AND MPL-1.0)"); // true
// package can be licensed under MPL-1.0 or Apache-2.0
// spdx implementation returns false currently.

satisfies("MPL-1.0 AND Apache-2.0", "GPL-3.0 OR MIT OR (Apache-2.0 AND MPL-1.0)"); // false
// this feels a bit natural, but conjuctive dual licensing is tricky
// the package author's AND means that user should obey restrictions from both MPL-1.0 and Apache-2.0, and only use common permissions
// the package user's AND means that we would like to use permissions from both licenses, and obey only common restrictions.
// ^- there you see a dualism.
```

This example is why I'd like to have _higher-level_ specification of `satisfies`, as when formulas are complicated, there should be a _pen-and-paper_ way to verify code works correctly.

**Comment by kemitchell** [comment]
I'm not sure whether `OR` should be read as exclusive or not. The meaning of "dual licensing" is indeed a bit murky in common usage, though there is at least one rigorous (and more restrictive) definition on the legal side.

The canonical use case for `AND` in a package license description is a library under one license that links a package of another license. A library binding, say.

**Comment by kemitchell** [comment]
I have split `satisfies` out into its own package, https://github.com/kemitchell/spdx-satisfies.js and https://npmjs.com/packages/spdx-satisfies.
